kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: tsm-pdl-cache
  namespace: tsm
  labels:
    team: tsm
    system: mottak
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        databases:
          - name: tsm-pdl-cache
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        tier: db-custom-1-3840
  image: {{image}}
  replicas:
    min: 2
    max: 5
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    failureThreshold: 10
    initialDelay: 20
    path: /internal/health
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
    inbound:
      rules:
        - application: macgyver
          namespace: teamsykmelding
        - application: pale-2-regler
          namespace: teamsykmelding
        - application: regulus-maximus
        - application: migrator
        - application: journey
        - application: tsm-manuell-api
        - application: syk-inn
        - application: syk-inn-api
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 700Mi
  kafka:
    pool: nav-prod
