ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [no.nav.tsm.pdl.cache.ApplicationKt.module]
  }
}

app {
  name = tsm-pdl-cache-local
}

postgres {
  url = "postgresql://localhost:7977/tsm-pdl-cache"
  url = ${?DB_URL}
  jdbc = "jdbc:"${postgres.url}
  username = "user"
  username = ${?DB_USERNAME}
  password = "password"
  password = ${?DB_PASSWORD}
}

kafka {
  config {
    "bootstrap.servers" = "localhost:9092"
    "bootstrap.servers" = ${?BOOTSTRAP_SERVERS}
    "security.protocol" = "PLAINTEXT"
  }
  pdlConsumer {
    longPoll: PT10S
    retryDelay: PT10S
  }
}
