ktor {
  deployment {
    port = 8080
    port = ${?PORT}
    # Allow long-poll to finish before shutting down
    shutdownTimeout: 20000
  }
  application {
    modules = [no.nav.tsm.pdl.cache.ApplicationKt.module]
  }
}

app {
  name = ${NAIS_POD_NAME}
}

postgres {
  jdbc = ${DB_JDBC_URL}
  username = ${DB_USERNAME}
  password = ${DB_PASSWORD}
}

kafka {
  config {
    "bootstrap.servers" = ${KAFKA_BROKERS}
    "security.protocol" = "SSL"
    "ssl.truststore.location" = ${KAFKA_TRUSTSTORE_PATH}
    "ssl.truststore.password" = ${KAFKA_CREDSTORE_PASSWORD}
    "ssl.truststore.type" = "jks"
    "ssl.keystore.location" = ${KAFKA_KEYSTORE_PATH}
    "ssl.keystore.password" = ${KAFKA_CREDSTORE_PASSWORD}
    "ssl.keystore.type" = "PKCS12"
  }
  pdlConsumer {
    longPoll: PT10S
    retryDelay: PT60S
  }
}
