[versions]
kotlin = "2.4.10"
logback = "1.6.3"
logbackEncoder = "9.0"
kafka = "4.3.1"

flyway = "13.3.0"
exposed = "1.4.0"
postgres = "42.7.13"

tsm-sykmeldinger-input = "29"

kotest-assertions = "6.2.4"
mockk = "1.14.11"
testcontainers = "2.0.5"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logbackEncoder" }
kafka-client = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }

# Database
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
exposed-date = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }

# TSM libs
tsm-sykmeldinger-input = { module = "no.nav.tsm.sykmelding:input", version.ref = "tsm-sykmeldinger-input" }

# Testing
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest-assertions" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
testcontainers-kafka = { module = "org.testcontainers:testcontainers-kafka", version.ref = "testcontainers" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
spotless = { id = "com.diffplug.spotless", version = "8.10.0" }
gradle-versions = { id = "com.github.ben-manes.versions", version = "0.61.0" }
