on:
  push:
    branches:
      - '**'
permissions:
  actions: read
  contents: read
  security-events: write
  packages: write
  id-token: write

jobs:
  build:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/gradle-21.yaml@feat/kotlin-app
    secrets: inherit
    with:
      app: 'tsm-pdl-cache'
